# Copyright 2020 Bilal Elmoussaoui <bil.elmoussaoui@gmail.com>
# SPDX-License-Identifier: Apache-2.0 OR MIT

on: [push, pull_request]

name: CI

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions-rs/cargo@v1
        with:
          command: build
      - uses: actions-rs/cargo@v1
        with:
          command: test

  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: cargo --version && rustc --version
      - run: cargo fmt --all --check

  toml_validation:
    runs-on: ubuntu-latest
    container:
      image: tamasfe/taplo:0.9.3
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: taplo lint
        run: taplo lint
      - name: taplo fmt
        run: taplo fmt --check --diff
